project:
  type: book
  output-dir: docs

execute:
  freeze: auto

language:
  section-title-appendices: "Apêndices"

book:
  title: "Avaliação do impacto da obrigatoriedade de freio ABS em caminhões na severidade dos sinistros"
  author:
  - name: Arthur Hideio Noguti
  - name: Dr. Jorge Tiago Bastos
    orcid: 0000-0001-6447-1504
  date: last-modified
  chapters:
    - index.qmd
    - introducao.qmd
    - metodologia.qmd
    - resultados.qmd
    - conclusao.qmd
    - ref.qmd
  twitter-card: true
  repo-url: https://github.com/arthurnoguti/Analise_PRF_quarto
  language: pt

csl: associacao-brasileira-de-normas-tecnicas.csl

format:
  html:
    theme: [cosmo, custom.scss]
    lang: pt
    fig-cap-location: top
    linkcolor: "#00496d"
    
