<style>
p {
  text-align: justify;  
  text-indent: 20px;   
}
</style>  

# Introdução    
***  


<p>O CONTRAN, por meio da Resolução 311/09 estabeleceu a obrigatoriedade do equipamento suplementar de segurança Airbag na frota veículos novos, assim como, por meio da Resolução 380/11, a obrigatoridade dos freios ABS. O objetivo deste documento é avaliar o impacto da obrigatoriedade do Airbag e ABS na severidade dos sinistros de trânsito. A pesquisa utilizou dados de sinistros nas rodovias federais brasileiras disponibilizados pela da Polícia Rodoviária Federal. 

## Estudos sobre o impacto de Airbags

<p>Um estudo baseado meta-análise realizado por Høye (2010) avaliou em diversos países os efeitos dos Airbags frontais nas mortes de condutores com e sem cinto de segurança, as variáveis incluíam veículos de diferentes portes e variados tipos de Airbags. Os resultados indicaram uma redução de 22% nas mortes nos sinistros em geral e uma redução de 18% para as colisões frontais com o uso de Airbag associado ao cinto de segurança. No entanto, não foi observada qualquer redução global da mortalidade entre os condutores sem cinto de segurança e, em alguns casos, o risco de mortalidade aumentou, especialmente em sinistros sem colisão enfatizando assim, a importância do controle das variáveis observadas, como o uso do cinto de segurança e a direção do impacto do veículo para avaliar com maior precisão eficácia dos Airbags como item de segurança veicular.  

<p>Viano (2024) detalhou um histórico de evolução dos benefícios e riscos de segurança dos Airbags com foco na análise de dados de campo. A pesquisa realizada nos Estados Unidos demonstrou que os Airbags, especialmente quando utilizados em conjunto com cintos de segurança, são eficazes na prevenção de mortes e ferimentos em colisões. Em geral, a redução do risco de mortes e lesões foi de 69,7% com uso de cinto e Airbags. Por fim, observou-se também riscos associados ao acionamento e ruptura de Airbags, incluindo casos de lesões e mortes relacionadas a isso, levando a necessidade de avanços no design do mesmo para mitigação de tais riscos.

<p>Ahmad et al., 2017 comparou os resultados de lesões nos ocupantes de veículos com e sem Airbags frontais usando dummies adultos em um cenário de teste de colisão frontal onde os veículos foram impelidos contra uma barreira estacionária a uma velocidade de 64 km/h para avaliar a eficácia do equipamento de segurança em estudo. Os dados de lesões nas extremidades superiores e na cabeça, foram coletados e analisados usando o Critério de Lesão na Cabeça (HIC) e o 3ms e foram calculados com base em medições de aceleração durante o pulso de colisão. Os resultados revelaram que as métricas de lesões na cabeça do condutor melhoraram 87% quando o Airbag estava presente e que o pico de aceleração 3ms que quantifica as medidas de impacto na região do tórax foi reduzida em 66%, diminuindo assim potenciais lesões. Para os passageiros dianteiros, os valores de aceleração HIC e 3ms foram reduzidos em 48% e 21%, respectivamente, ao comparar o veículo com e sem Airbag.  

<p>Nos Estados Unidos, usando dados entre 1993 e 2000, Itans e Stergiannis (2011) observaram que os Airbags podem reduzir a incidência de fatalidades em colisões frontais veiculares em aproximadamente 25% quando comparados à cenários onde apenas os cintos de segurança são usados, além de reduzir as lesões dos passageiros em até 50%. No entanto, os autores salientaram que o uso ou acionamento inadequado do mesmo pode causar lesões graves, incluindo queimaduras diversas pela liberação de gases, lesões oculares 2,5%, lesões e fraturas em extremidades superiores 2,7% e 4,4%, respectivamente.  


## Estudos sobre o impacto de ABS  

<p>Nos Estados Unidos, Bhalla e Gleason (2020) desenvolveram um estudo com o objetivo de avaliar o impacto da implementação de tecnologias de segurança veicular na América Latina e no Caribe para reduzir mortes e lesões no trânsito. A metodologia envolveu o uso de dados sobre mortalidade e sinistros de vários países da região e a estimativa dos benefícios da difusão das tecnologias de segurança veicular em termos da redução da mortalidade e do indicador DALY (Disability-Adjusted Life Years). Especificamente, o uso do controle eletrônico de estabilidade juntamente com os freios ABS poderia resultar em 19,40% menos mortes e um indicador DALY 17% menor. 

<p>Com o objetivo comparar as taxas anuais de sinistros (RTCs) em carros  equipados com e sem Sistema de Frenagem Antibloqueio (ABS) de um mesmo fabricante de veículos no Irã, (Khorasani-Zavareh et al., 2013) coletou os dados estudados através de uma pesquisa telefônica estruturada para obter informações sobre o número de sinistros, perdas financeiras e percepções dos motoristas em relação ao ABS. A amostra foi composta por 1.232 condutores de veículos equipados com ABS e 3.123 sem ABS, selecionados por meio de amostragem aleatória simples do cadastro da Organização Central de Seguros. Entre os motoristas de veículos equipados com ABS, 61,1% relataram situações em que acreditavam que o sistema havia evitado uma colisão e 44,1% dos motoristas com ABS não sabiam como usar o ABS de forma eficaz. O estudo descobriu também que a incidência de RTCs devido a falha de freio foi maior no grupo sem ABS, com uma taxa de 50,3 RTCs por 1.000 veículos/ano em comparação com 30,0 RTCs por 1.000 veículos/ano para os com ABS.  

<p>O estudo conduzido por Zulhilm et al., 2020 teve como objetivo analisar o efeito da frenagem de emergência sem Sistema de Frenagem Antibloqueio (ABS) no comportamento da dinâmica de veículos. Com o uso de um veículo de teste (um carro nacional da Malásia, o Proton Persona) instrumentado com sensores e sistemas de aquisição de dados. Foram tomadas precauções de segurança, incluindo a utilização de uma pista de testes fechada e um motorista experiente. O estudo envolveu travagens de emergência a 60 km/h em estradas molhadas, com dados registados e analisados para fins de consistência. Os resultados indicaram que sem o ABS, o veículo enfrentava desafios na manutenção da estabilidade e da direção durante a travagem de emergência, destacando a importância do ABS na melhoria do desempenho da frenagem veicular e consequentemente da segurança rodoviária em geral.  

